// This file is part of DwellClick <https://pilotmoon.com/dwellclick/>
// SPDX-License-Identifier: Apache-2.0

/*
Master include file for NMKit
*/
#ifndef NMLocalS
#define NMLocalS(nsstr, comment) NSLocalizedStringFromTable(nsstr, @"NMKit", comment)
#endif

#import "NMAppMonitor.h"
#import "NMAppSupportDir.h"
#import "NMAppUtils.h"
#import "NMBlockUtils.h"
#import "NMBrowserHelper.h"
#import "NMBubbleCloseButton.h"
#import "NMBubbleWindow.h"
#import "NMBubbleWindowView.h"
#import "NMCUtils.h"
#import "NMCommander.h"
#import "NMConfigUtils.h"
#import "NMCoreUtils.h"
#import "NMCursorUtils.h"
#import "NMEscapableItem.h"
#import "NMEventUtils.h"
#import "NMFloatUtils.h"
#import "NMGeometryUtils.h"
#import "NMImageButton.h"
#import "NMImageButtonCell.h"
#import "NMInitialDefaults.h"
#import "NMKeyCombo.h"
#import "NMKeyCommander.h"
#import "NMKeyConverter.h"
#import "NMKeyPresser.h"
#import "NMLinks.h"
#import "NMLog.h"
#import "NMLoginItemsController.h"
#import "NMMouseUtils.h"
#import "NMNubWindow.h"
#import "NMNubWindowView.h"
#import "NMPoint.h"
#import "NMPopupController.h"
#import "NMPopupWindow.h"
#import "NMPopupWindowBackgroundView.h"
#import "NMPopupWindowBorderView.h"
#import "NMPopupWindowButton.h"
#import "NMPopupWindowButtonCell.h"
#import "NMRegexUtils.h"
#import "NMStartAtLogin.h"
#import "NMStartAtLogin2024.h"
#import "NMState.h"
#import "NMStateMachine.h"
#import "NMStatusBubbleWindow.h"
#import "NMStatusItemController.h"
#import "NMSugarButton.h"
#import "NMSugarButtonCell.h"
#import "NMSuperFastHash.h"
#import "NMUIElement.h"
#import "NMUIElementHelper.h"
#import "NMUniversalAccessHelper.h"
#import "NMUniversalMonitor.h"
#import "NSBezierPath+NMNub.h"
#import "NSImage+NMCopySize.h"
#import "NSMutableDictionary+NMSafe.h"
#import "NSObject+NMObservePrefs.h"
#import "NSWindow+NMAdditions.h"
